# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 524)
        MainWindow.setMinimumSize(QtCore.QSize(4, 0))
        MainWindow.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/network.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        MainWindow.setProperty("frameless", True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.widget.setStyleSheet("#widget {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 1);\n"
"}")
        self.widget.setObjectName("widget")
        self.frame_main = QtWidgets.QFrame(self.widget)
        self.frame_main.setGeometry(QtCore.QRect(0, 40, 600, 460))
        self.frame_main.setStyleSheet("QPushButton:hover {\n"
"    padding-bottom: 8px;\n"
"    padding-left:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-right:3px;\n"
"}\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_tab = QtWidgets.QFrame(self.frame_main)
        self.frame_tab.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_tab.setStyleSheet("QFrame#frame_tab {\n"
"    border: none; \n"
"    border-bottom: 1px solid black; \n"
"}\n"
"QFrame#frame_tab QPushButton {\n"
"    border-top-right-radius: 10px; \n"
"    border: 1px solid #ccc; \n"
"    background-color: #f8f8f8; \n"
"    margin-bottom:0;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_tab.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tab.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tab.setObjectName("frame_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_tab_main = QtWidgets.QPushButton(self.frame_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tab_main.sizePolicy().hasHeightForWidth())
        self.pushButton_tab_main.setSizePolicy(sizePolicy)
        self.pushButton_tab_main.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_tab_main.setStyleSheet("margin-left:5px;")
        self.pushButton_tab_main.setObjectName("pushButton_tab_main")
        self.horizontalLayout.addWidget(self.pushButton_tab_main, 0, QtCore.Qt.AlignBottom)
        self.pushButton_tab_manege = QtWidgets.QPushButton(self.frame_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tab_manege.sizePolicy().hasHeightForWidth())
        self.pushButton_tab_manege.setSizePolicy(sizePolicy)
        self.pushButton_tab_manege.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_tab_manege.setStyleSheet("")
        self.pushButton_tab_manege.setObjectName("pushButton_tab_manege")
        self.horizontalLayout.addWidget(self.pushButton_tab_manege, 0, QtCore.Qt.AlignBottom)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_tab)
        self.stackedWidget_tab = QtWidgets.QStackedWidget(self.frame_main)
        self.stackedWidget_tab.setObjectName("stackedWidget_tab")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.frame = QtWidgets.QFrame(self.page_main)
        self.frame.setGeometry(QtCore.QRect(130, 50, 340, 310))
        self.frame.setStyleSheet("*{\n"
"    font: 10pt \"微软雅黑\";\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 1px solid #dcdcdc;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #dcdcdc;\n"
"\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 342, 325))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_username.sizePolicy().hasHeightForWidth())
        self.lineEdit_username.setSizePolicy(sizePolicy)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(340, 50))
        self.lineEdit_username.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_5.addWidget(self.lineEdit_username)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_5.addWidget(self.lineEdit_password)
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 35))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_login = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_login.sizePolicy().hasHeightForWidth())
        self.pushButton_login.setSizePolicy(sizePolicy)
        self.pushButton_login.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_login.setMaximumSize(QtCore.QSize(16777215, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login.setIcon(icon1)
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout_3.addWidget(self.pushButton_login)
        self.pushButton_dislogin = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dislogin.sizePolicy().hasHeightForWidth())
        self.pushButton_dislogin.setSizePolicy(sizePolicy)
        self.pushButton_dislogin.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_dislogin.setMaximumSize(QtCore.QSize(16777215, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dislogin.setIcon(icon2)
        self.pushButton_dislogin.setObjectName("pushButton_dislogin")
        self.horizontalLayout_3.addWidget(self.pushButton_dislogin)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.pushButton_login_2 = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_login_2.sizePolicy().hasHeightForWidth())
        self.pushButton_login_2.setSizePolicy(sizePolicy)
        self.pushButton_login_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_login_2.setMaximumSize(QtCore.QSize(16777215, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login_2.setIcon(icon3)
        self.pushButton_login_2.setObjectName("pushButton_login_2")
        self.verticalLayout_5.addWidget(self.pushButton_login_2)
        self.stackedWidget_message = QtWidgets.QStackedWidget(self.widget1)
        self.stackedWidget_message.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget_message.setStyleSheet("QLabel{\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        self.stackedWidget_message.setObjectName("stackedWidget_message")
        self.black_text = QtWidgets.QWidget()
        self.black_text.setMinimumSize(QtCore.QSize(0, 0))
        self.black_text.setObjectName("black_text")
        self.label_black_message = QtWidgets.QLabel(self.black_text)
        self.label_black_message.setGeometry(QtCore.QRect(0, 0, 340, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_black_message.sizePolicy().hasHeightForWidth())
        self.label_black_message.setSizePolicy(sizePolicy)
        self.label_black_message.setMinimumSize(QtCore.QSize(0, 0))
        self.label_black_message.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_black_message.setText("")
        self.label_black_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_black_message.setObjectName("label_black_message")
        self.stackedWidget_message.addWidget(self.black_text)
        self.green_text = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.green_text.sizePolicy().hasHeightForWidth())
        self.green_text.setSizePolicy(sizePolicy)
        self.green_text.setObjectName("green_text")
        self.label_green_message = QtWidgets.QLabel(self.green_text)
        self.label_green_message.setGeometry(QtCore.QRect(0, 0, 340, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_green_message.sizePolicy().hasHeightForWidth())
        self.label_green_message.setSizePolicy(sizePolicy)
        self.label_green_message.setMinimumSize(QtCore.QSize(0, 0))
        self.label_green_message.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_green_message.setText("")
        self.label_green_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_green_message.setObjectName("label_green_message")
        self.stackedWidget_message.addWidget(self.green_text)
        self.red_text = QtWidgets.QWidget()
        self.red_text.setObjectName("red_text")
        self.label_red_message = QtWidgets.QLabel(self.red_text)
        self.label_red_message.setGeometry(QtCore.QRect(0, 0, 340, 35))
        self.label_red_message.setMinimumSize(QtCore.QSize(0, 0))
        self.label_red_message.setStyleSheet("color:rgb(255, 0, 0);")
        self.label_red_message.setText("")
        self.label_red_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_red_message.setObjectName("label_red_message")
        self.stackedWidget_message.addWidget(self.red_text)
        self.verticalLayout_5.addWidget(self.stackedWidget_message)
        self.stackedWidget_tab.addWidget(self.page_main)
        self.page_manege = QtWidgets.QWidget()
        self.page_manege.setObjectName("page_manege")
        self.frame_2 = QtWidgets.QFrame(self.page_manege)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 601, 431))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.time_edit = QtWidgets.QTimeEdit(self.splitter)
        self.time_edit.setObjectName("time_edit")
        self.file_path_edit = QtWidgets.QLineEdit(self.splitter)
        self.file_path_edit.setObjectName("file_path_edit")
        self.select_file_btn = QtWidgets.QPushButton(self.splitter)
        self.select_file_btn.setObjectName("select_file_btn")
        self.verticalLayout_4.addWidget(self.splitter)
        self.task_name_label = QtWidgets.QLabel(self.frame_2)
        self.task_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.task_name_label.setObjectName("task_name_label")
        self.verticalLayout_4.addWidget(self.task_name_label)
        self.create_btn = QtWidgets.QPushButton(self.frame_2)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout_4.addWidget(self.create_btn)
        self.query_btn = QtWidgets.QPushButton(self.frame_2)
        self.query_btn.setObjectName("query_btn")
        self.verticalLayout_4.addWidget(self.query_btn)
        self.delete_btn = QtWidgets.QPushButton(self.frame_2)
        self.delete_btn.setObjectName("delete_btn")
        self.verticalLayout_4.addWidget(self.delete_btn)
        self.task_table = QtWidgets.QTableWidget(self.frame_2)
        self.task_table.setTabletTracking(True)
        self.task_table.setStyleSheet("")
        self.task_table.setFrameShape(QtWidgets.QFrame.Box)
        self.task_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_table.setLineWidth(1)
        self.task_table.setMidLineWidth(0)
        self.task_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.task_table.setAutoScroll(False)
        self.task_table.setAutoScrollMargin(0)
        self.task_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.task_table.setProperty("showDropIndicator", False)
        self.task_table.setDragDropOverwriteMode(False)
        self.task_table.setAlternatingRowColors(True)
        self.task_table.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.task_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.task_table.setGridStyle(QtCore.Qt.SolidLine)
        self.task_table.setCornerButtonEnabled(False)
        self.task_table.setColumnCount(0)
        self.task_table.setObjectName("task_table")
        self.task_table.setRowCount(0)
        self.task_table.horizontalHeader().setVisible(False)
        self.task_table.horizontalHeader().setSortIndicatorShown(False)
        self.task_table.horizontalHeader().setStretchLastSection(True)
        self.task_table.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.task_table)
        self.stackedWidget_tab.addWidget(self.page_manege)
        self.verticalLayout.addWidget(self.stackedWidget_tab)
        self.frame_title = QtWidgets.QFrame(self.widget)
        self.frame_title.setGeometry(QtCore.QRect(0, 0, 600, 40))
        self.frame_title.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.frame_title.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    padding-bottom: 8px;\n"
"    padding-left:8px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-right:3px;\n"
"}\n"
"#pushButtom_title {\n"
"    font: 10pt \"微软雅黑\";\n"
"    padding: 0;\n"
"}\n"
"#frame_title {\n"
"    border: none; \n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border: 1px solid rgb(204, 204, 204); \n"
"}")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_2.setContentsMargins(0, 3, 8, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtom_title = QtWidgets.QPushButton(self.frame_title)
        self.pushButtom_title.setStyleSheet("margin-left: 10px;")
        self.pushButtom_title.setIcon(icon)
        self.pushButtom_title.setIconSize(QtCore.QSize(30, 30))
        self.pushButtom_title.setObjectName("pushButtom_title")
        self.horizontalLayout_2.addWidget(self.pushButtom_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_minizing = QtWidgets.QPushButton(self.frame_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_minizing.sizePolicy().hasHeightForWidth())
        self.pushButton_minizing.setSizePolicy(sizePolicy)
        self.pushButton_minizing.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_minizing.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/minizing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_minizing.setIcon(icon4)
        self.pushButton_minizing.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_minizing.setObjectName("pushButton_minizing")
        self.horizontalLayout_2.addWidget(self.pushButton_minizing)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_close.setStyleSheet("")
        self.pushButton_close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon5)
        self.pushButton_close.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_tab.setCurrentIndex(0)
        self.stackedWidget_message.setCurrentIndex(0)
        self.pushButton_close.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_minizing.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "广西科师校园网登录助手"))
        self.pushButton_tab_main.setText(_translate("MainWindow", "首页"))
        self.pushButton_tab_manege.setText(_translate("MainWindow", "定时任务管理"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "请输入学号/工号"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.checkBox.setText(_translate("MainWindow", "记住密码"))
        self.pushButton_login.setText(_translate("MainWindow", "登录"))
        self.pushButton_dislogin.setText(_translate("MainWindow", "下线"))
        self.pushButton_login_2.setText(_translate("MainWindow", "根据账号密码生成一键登录文件"))
        self.time_edit.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.select_file_btn.setText(_translate("MainWindow", "选择文件"))
        self.task_name_label.setText(_translate("MainWindow", "文件名："))
        self.create_btn.setText(_translate("MainWindow", "创建任务"))
        self.query_btn.setText(_translate("MainWindow", "查询任务"))
        self.delete_btn.setText(_translate("MainWindow", "删除任务"))
        self.task_table.setSortingEnabled(True)
        self.pushButtom_title.setText(_translate("MainWindow", "广西科师校园网登录助手"))
import window_rc
